version: '3.8'
services:
  api1:
    image: hanseld28/rinha-backend-rust-api:1.0.1
    environment:
      HOST: 0.0.0.0
      PORT: 80
      DATABASE_URL: postgresql://postgres:2309@db:5432/root?schema=public
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.6GB'

  api2:
    image: hanseld28/rinha-backend-rust-api:1.0.1
    environment:
      HOST: 0.0.0.0
      PORT: 80
      DATABASE_URL: postgresql://postgres:2309@db:5432/root?schema=public
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.6GB'

  nginx:
    image: hanseld28/rinha-nginx:1.0.1
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.3GB'

  db:
    image: hanseld28/rinha-postgres:1.0.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "2309"
      POSTGRES_DB: "root"
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: '1.05'
          memory: '1.5GB'
